Попробовал изменить сообщения
Y-Doka/surge-preview pull request #2
Opened 2021-05-24 11:40 UTC by igsekor

Сделал сообщения минималистичнее.

@pepelsbey, @nlopin, @furtivite посмотрите, пожалуйста.

2021-05-24 15:22 UTC, pepelsbey requested changes
А карты кода и связанные с ними файлы нужны? :)

Предложил немного другие формулировки.

2021-05-24 15:22 UTC, pepelsbey commented on src/helpers.ts
> +  return '<sub>Сообщение создано автоматически</sub>';
Я бы футер в принципе убрал, и так понятно по автору, что автоматически.

2021-05-24 15:22 UTC, pepelsbey commented on src/main.ts
> +Превью контента из ${gitCommitSha} опубликовано и доступно по [ссылке](https://${url})
```suggestion
[Превью контента](https://${url}) из ${gitCommitSha} опубликовано.
```

2021-05-24 15:22 UTC, pepelsbey commented on src/main.ts
> +[Превью](https://${url}) ${gitCommitSha} удалено, поскольку PR был закрыт.
```suggestion
[Превью](https://${url}) ${gitCommitSha} удалено, PR уже закрыт.
```

2021-05-24 15:22 UTC, pepelsbey commented on src/main.ts
> +Ошибка публикации превью для контента из ${gitCommitSha}. [Логи](https://github.com/${
```suggestion
Ошибка публикации превью для контента из ${gitCommitSha}. Подробнее [в логах](https://github.com/${
```

2021-05-24 15:22 UTC, pepelsbey commented on src/main.ts
> +Идёт публикация превью для контента из ${gitCommitSha}... [Логи](${buildingLogUrl})
```suggestion
Идёт публикация превью для контента из ${gitCommitSha}… Подробнее [в логах](${buildingLogUrl}).
```

2021-05-24 15:35 UTC, igsekor commented on src/helpers.ts
> +  return '<sub>Сообщение создано автоматически</sub>';
Готово! :)

2021-05-24 15:38 UTC, igsekor commented
> А карты кода и связанные с ними файлы нужны? :)

Да не хочется сильно уходить от оригинала. Вдруг они баг поправят? Ну и не мешают они нам, вроде бы.

2021-05-24 16:58 UTC, pepelsbey approved these changes

2021-05-26 18:49 UTC, nlopin approved these changes

2021-05-26 18:50 UTC, merged